# Generated by Django 5.2.4 on 2025-08-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book', max_length=200)),
                ('author', models.CharField(help_text='The author of the book', max_length=100)),
                ('isbn', models.CharField(blank=True, help_text='ISBN number (optional)', max_length=13, null=True, unique=True)),
                ('publication_date', models.DateField(blank=True, help_text='Date when the book was published', null=True)),
                ('pages', models.PositiveIntegerField(blank=True, help_text='Number of pages in the book', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
    ]
